baseURL: http://wogus00.github.io/
languageCode: en-us
title: Jae's Blog
paginate: 5
theme: hugo-theme-stack

languages:
    en:
        languageName: English
        title: Jae's Blog
        description: blog description in English
        weight: 1

    ko:
        languageName: 한국어
        title: Jae's Blog
        description: 블로그 설명
        weight: 2

        
            
params:
    mainSections:
        - posts
    rssFullContent: true

    footer:
        since: 2023
        customText: 
    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 EST
    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

    article:
        math: false
        toc: true
        readingTime: false
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/wogus00/
          params:
              icon: brand-github

    sidebar:
        emoji: 🇨🇦
        avator:
            enabled: true
            local: true
            src: /img/memoji.png

permalinks:
    post: /posts/:slug/
    page: /:slug/

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4